### ISSUE TITLE
Prepare UI for our classic model

### ISSUE THREAD

**Issue by hatskier** [redstone-finance/redstone-app#71]
We would like to implement UI which will represent current state of our data feeds deployed on different chains in the [classic model](https://docs.redstone.finance/docs/smart-contract-devs/get-started/redstone-classic).

**STEP 1**
(Simple component)
Display information from our relayers manifests in a human readable format (UI) with update triggers conditions and links to the corresponding contracts. You can fetch all required infromation from this url: https://p6s64pjzub.execute-api.eu-west-1.amazonaws.com/dev/execute

**STEP 2**
(Getting data from smart-contract)
Add live info (e.g. about the latest update). You can get time of the latest update using `getBlockTimestampFromLatestUpdate` function on the adapter smart contract. To get the latest value you can use the `getValueForDataFeed(bytes32 dataFeedId)` function

**STEP 3**
(Simple chart)
Implement a subpage showing details of a relayer with a chart. The data points could be taken either from smart contract or from external API (like etherscan): https://etherscan.io/address/0xdDb6F90fFb4d3257dd666b69178e5B3c5Bf41136#events
It's enough to implement just one page with the data coming from the url above

### Key details
- Work on https://github.com/redstone-finance/redstone-app
- Reuse existing components
- Let's research what are the best way to get valid details about chains, like urls to blockchain explorers, logos, names (maybe smth like https://chainlist.org/chain/42161, maybe we will just hardcode it in our own json file)

**Comment by Oyase-shinobi** [comment]
Hello @hatskier 
I would love to engage in your team and work with your team
